### ISSUE TITLE
Project presentation - Cheder 4.03

### ISSUE THREAD

**Issue by dr0p** [kuzmir/kuzmir_app#6]
According to our FB group, we want to present our project in Cheder in the begining of march https://www.facebook.com/events/1536706533276089/.

List of functionalities is needed because of that. @EmiMaj  can you name them ?

**Comment by EmiMaj** [comment]
@dr0p I guess it's not possible to show application working in the beginning of March. I'd rather explain the concept based on wireframes and visual design only. We have list of functionalities described as users stories, that's it. Should I provide any other list / document?

**Comment by dr0p** [comment]
@EmiMaj I think that provided users' stories are sufficient ;)
